### ISSUE TITLE
Correctly recognize (and warn on) repeated message fields

### ISSUE THREAD

**Issue by mishas** [nelfin/pylint-protobuf#15]
This plugin correctly recognizes native repeated fields (as in `repeated int32 filed = 1;`), but doesn't recognize repeated fields of messages (as in `repeated MyMessage field = 2;`).

For those fields I get errors for both the `.add()` and the `.extends()` methods.
(Please note that repeated message fields do not have the `.append()` field).

**Comment by nelfin** [comment]
This is a known issue, there's a bunch of XFAIL tests in `tests/test_repeated.py` (actually only one now that I check it). I should make it clearer in the readme, and I'll prioritise working on it.

**Comment by nelfin** [comment]
> (Please note that repeated message fields do not have the .append() field).
I assume this is meant to read "repeated scalar fields do not have the .append() method"

I'm pleased to report that repeated fields are fully supported as of the 0.18.x release. Sorry for the wait!

**Comment by nelfin** [comment]
Let me know if you have any further issues with repeated fields
