### ISSUE TITLE
Plugin doesn't support "special" fields (repeated, struct, timestamp)

### ISSUE THREAD

**Issue by Kami** [nelfin/pylint-protobuf#20]
This plugin doesn't appear to be supporting field types such as ``repeated``, ``google.protobuf.Timestamp`` and ``google.protobuf.Struct``.

In fact, I believe some of that (timestamps?) worked in a previous release, but it seemed to have broken in the latest one.

Here is a simple code which demonstrates a problem:

## Environment

```bash
$ python --version
Python 3.7.4
$ pip show pylint-protobuf
Name: pylint-protobuf
Version: 0.11
Summary: A plugin for making Pylint aware of the fields of protobuf-generated classes
Home-page: https://github.com/nelfin/pylint-protobuf
Author: Andrew Haigh
Author-email: hello@nelf.in
License: MIT
Location: /home/kami/.virtualenvs/waas-py3.7/lib/python3.7/site-packages
Requires: astroid, pylint
Required-by: 
```

## Protobuf definition file

```protobuf
syntax = "proto3";

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

message Item {
    string key = 1;
    string value = 2;
}

message Action {
    string key = 1;

    string name = 2;

    repeated Item items = 3;

    google.protobuf.Timestamp timestamp = 4;

    google.protobuf.Struct values = 5;
}
```

## Python code which demonstrates the problem

```python
import action_pb2

action_pb = action_pb2.Action()

# This should all work
action_pb.key = 'key'
action_pb.name = 'foo bar'

item1 = action_pb2.Item()
item1.key = 'key1'
item1.value = 'value1'

action_pb.items.append(item1)  # this doesn't work but it should
action_pb.timestamp.GetCurrentTime()  # this doesn't work but it should
action_pb.values.update({'foo1': 'bar1', 'foo2': 2})  # this doesn't work but it should
```

## Pylint output

```bash
$ pylint -E --load-plugins pylint_protobuf --rcfile=./lint-configs/.pylintrc test.py
************* Module test
test.py:13:0: E5901: Field 'append' does not appear in the declared fields of protobuf-generated class 'action_pb2.Action.items' and will raise AttributeError on access (protobuf-undefined-attribute)
test.py:14:0: E5901: Field 'timestamp' does not appear in the declared fields of protobuf-generated class 'action_pb2.Action' and will raise AttributeError on access (protobuf-undefined-attribute)
test.py:15:0: E5901: Field 'values' does not appear in the declared fields of protobuf-generated class 'action_pb2.Action' and will raise AttributeError on access (protobuf-undefined-attribute)
```

**Comment by Kami** [comment]
EDIT: It looks like there is already an existing issue for handling repeated message types - #15.

Are all of those known issues? Is anyone already working on it? Depending on how hard the fix / change would be, perhaps I can also look into it.

**Comment by nelfin** [comment]
Hi @Kami, looks like it's aggressively ignoring well-known-types. I made the decision to not warn on missing fields on WKTs for a bit and work on them later (#14), it shouldn't be warning about the fields themselves (just fields on the fields).

Re: repeated fields, just me at the moment. I've pushed some in-progress code to `wip/repeated` if you'd like to use that as a jumping-off point.

**Comment by nelfin** [comment]
Ooops, sorry I had a git hook that prevented me from pushing that earlier. I've pushed that wip branch now.

**Comment by nelfin** [comment]
There's been a few changes responsible for this but as of 0.18.1 your test file no longer raises any warnings.

**Comment by nelfin** [comment]
Let me know if this causes you any more troubles in the future
