### ISSUE TITLE
False Positive E5903 on bytes field

### ISSUE THREAD

**Issue by gal-simhi** [nelfin/pylint-protobuf#48]
Given the below protobuf definition and this code:
![image](https://user-images.githubusercontent.com/67221421/114300205-c2a9a800-9ac7-11eb-93ad-7c0b0f121a18.png)
![image](https://user-images.githubusercontent.com/67221421/114300213-cb9a7980-9ac7-11eb-8379-26cd05f6d89a.png)

we get this warning (which we shouldn't):
`E5903: Field "ConnectionIdProtobuf.src_ip" is of type 'str' and value <class 'bytes'> will raise TypeError at runtime (protobuf-type-error)
`

I believe the issue is in line 102, should be `bytes` ;)
https://github.com/nelfin/pylint-protobuf/blob/2a99f4cec5a590d7ecb01ca7411d7f6072eb186c/pylint_protobuf/transform.py#L102

**Comment by nelfin** [comment]
> I believe the issue is in line 102, should be bytes ;)

Haha, I reckon so. Thanks for the report @gal-simhi

**Comment by nelfin** [comment]
This should be fixed in `pip install git+https://github.com/nelfin/pylint-protobuf@af3d4856db6c743138ea0b78990ed8830779b79b`

**Comment by gal-simhi** [comment]
> This should be fixed in `pip install git+https://github.com/nelfin/pylint-protobuf@af3d4856db6c743138ea0b78990ed8830779b79b`

Great!  Thanks for the quick solution.
